[package]
name = "pbnjam"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.39"
cpal = "0.16.0"
dasp_signal = "0.11.0"
hound = "3.5.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
